In [ ]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
plt.rcParams["animation.html"] = "jshtml"
matplotlib.rcParams['animation.embed_limit'] = 2**128

import numpy as np
import pandas as pd
import seaborn as sns
sns.set()

import time
import datetime

from Models.Fire import Fire
from Models.Firefighter import Firefighter
from Models.FireRescueModel import FireRescueModel

model = FireRescueModel(strategy="intelligent")

ITERATIONS = 1
i = 0

while not(model.defeat()) and not(model.victory()) and i < ITERATIONS:
    model.step()
    i += 1

if (model.victory()):
    print("Players won")
elif (model.defeat()):
    print("Players Lost")
    print("Damage: ", model.damageTokens)
    print("Victims Lost: ", model.victimsLost)
else:
    print("Times up")

allAgentsInfo = model.datacollector.get_agent_vars_dataframe()
allAgentsInfo.info()

allGrids = model.datacollector.get_model_vars_dataframe()
allGrids.info()

# fig, axs = plt.subplots(figsize = (4, 4))
# axs.set_xticks([])
# axs.set_yticks([])
# patch = plt.imshow(allGrids.iloc[0, 0], cmap = plt.cm.binary)

# def animate(i):
#     patch.set_data(allGrids.iloc[i, 0])

# anim = animation.FuncAnimation(fig, animate, frames = model.steps)

# anim

Could not import SolaraViz. If you need it, install with 'pip install --pre mesa[viz]'
(1, 3)
(1, 3) (2, 4)
Neighbors:
0 0 0 0
(1, 2) (2, 3) (1, 4)
0 0 0 0
(1, 3) (2, 4)
3 [(1, 3), (1, 4), (2, 4)]
(6, 3)
(6, 3) (5, 1)
Neighbors:
0 0 0 0
(6, 4) (5, 3)
0 0 0 0
(6, 3) (5, 4) (4, 3)
0 0 0 0
(5, 3) (4, 4) (3, 3)
0 0 0 0
(5, 3) (6, 4) (4, 4)
0 1 0 0
(6, 3) (7, 4) (5, 4)
0 0 0 1
(4, 3) (3, 4) (2, 3)
1 0 0 0
(4, 3) (5, 4) (3, 4)
0 0 0 1
(7, 3) (8, 4) (6, 4)
0 0 0 0
(8, 3) (7, 4)
0 1 0 0
(2, 2) (3, 3) (2, 4) (1, 3)
0 0 0 0
(2, 1) (3, 2) (2, 3) (1, 2)
0 0 0 0
(3, 1) (2, 2) (1, 1)
0 1 0 0
(4, 1) (3, 2) (2, 1)
0 0 0 1
(5, 1) (4, 2) (3, 1)
10 [(6, 3), (5, 3), (4, 3), (3, 3), (2, 3), (2, 2), (2, 1), (3, 1), (4, 1), (5, 1)]
(6, 1)
(6, 1) (7, 5)
Neighbors:
0 0 0 0
(7, 1) (6, 2)
0 0 0 1
(6, 1) (7, 2) (5, 2)
0 0 0 0
(7, 1) (8, 2) (6, 2)
0 0 0 0
(8, 1) (7, 2) (6, 1)
1 0 0 0
(8, 1) (7, 2)
0 1 0 0
(5, 1) (6, 2) (4, 2)
0 0 0 0
(8, 2) (7, 1)
0 0 0 0
(4, 1) (5, 2)
0 0 0 0
(5, 2) (4, 1)
0 0 0 1
(5, 1) (4, 2) (3, 1)
0 1 0 0
(4, 1) (3, 2) (2, 1)
0 0 0 0
(3, 1) (2, 2)
0 0 0 0
(2, 1) (3, 2) (2, 3) (1, 2)
0 1 0 0
(2, 2) (3, 3) (2, 4) (1, 3)
0 0 0 0
(2, 3) (1, 4)
0 0 0 1
(4, 3) (3, 4) (2, 3)
0 0 0 0
(3, 3) (4, 4)
1 0 0 0
(4, 3) (5, 4) (3, 4)
0 0 0 0
(5, 3) (6, 4) (4, 4)
0 1 0 0
(6, 3) (7, 4) (5, 4)
0 0 0 1
(7, 3) (8, 4) (6, 4)
0 0 0 0
(8, 3) (7, 4)
0 0 0 0
(8, 3) (7, 4)
0 0 0 0
(6, 4) (5, 3)
0 0 1 0
(8, 4) (7, 3)
0 0 0 0
(6, 3) (5, 4) (4, 3)
0 0 0 0
(5, 3) (4, 4) (3, 3)
0 0 0 0
(6, 3) (5, 4) (4, 3)
0 0 0 0
(6, 4) (5, 3)
0 0 0 0
(1, 3) (2, 4)
0 0 0 0
(1, 2) (2, 3) (1, 4)
0 0 0 0
(3, 1) (2, 2) (1, 1)
0 0 0 0
(1, 1) (2, 2) (1, 3)
0 0 0 0
(2, 1) (1, 2)
1000000 [(7, 5)]
(8, 4)
No more POIs to be found
{(2, 4), (5, 1), (7, 5)}
No more POIs to be found
{(2, 4), (5, 1), (7, 5)}
No more POIs to be found
{(2, 4), (5, 1), (7, 5)}
Times up
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6 entries, (np.int64(1), np.int64(6)) to (np.int64(1), np.int64(3))
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Position  6 non-null      object
dtypes: object(1)
memory usage: 489.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Steps           1 non-null      int64
 1   VictimsRescued  1 non-null      int64
 2   VictimsLost     1 non-null      int64
 3   NewFire         1 non-null      object
 4   Dices           1 non-null      object
 5   DamageTokens    1 non-null      int64
 6   ChangedPOIs     1 non-null      object
dtypes: int64(4), object(3)
memory usage: 188.0+ bytes

In [ ]:
result = pd.DataFrame(allGrids)
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 2, 'black': 1}",0,[]

In [ ]:
result

,Steps,VictimsRescued,VictimsLost,NewFire,Dices,DamageTokens,ChangedPOIs
0,0,0,0,[],"{'red': 2, 'black': 1}",0,[]